site:
  appname: ssh-web-console
  listen_addr: :2222
  runmode: prod
  deploy_host: console.hpc.gensh.me

prod:
  # http path of static files and views
  static_prefix: /

dev: # config used in debug mode.
  # https prefix of static files only
  static_prefix: /static/
  # redirect static files requests to this address, redirect "static_prefix" to "static_redirect"
  # for example, static_prefix is "/static", static_redirect is "localhost:8080/dist",
  # this will redirect all requests having prefix "/static" to "localhost:8080/dist"
  static_redirect: "localhost:8080"
  static_dir: ./dist/ # if static_redirect is empty, http server will read static file from this dir.
  views_prefix: / #
  views_dir: views/ # views(html) directory.

ssh:
  #  io_mode: 1  # the mode reading data from ssh server: channel mode (0) OR session mode (1)
  buffer_checker_cycle_time: 60 # check buffer every { buffer_checker_cycle_time } ms. if buffer is not empty , then send buffered data back to client(browser/webSocket)
jwt:
  jwt_secret: secret.console.hpc.gensh.me
  token_lifetime: 7200
  issuer: issuer.ssh.gensh.me
  query_token_key: _t
